import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function SecurityRadar() {
  return (
    <div class="lg:col-span-1">
      <div class="text-card-foreground w-full h-full flex flex-col items-stretch bg-white/80 backdrop-blur-md shadow-xl border-0 rounded-2xl">
        <div class="flex flex-col space-y-1.5 p-6 pb-4">
          <div class="text-lg font-bold text-gray-800 tracking-tight">
            Security Radar Dashboard
            <span class="text-sm font-normal text-gray-500 ml-2">
              (114 total records)
            </span>
          </div>
        </div>
        <div class="p-6 pt-0 relative flex-1 px-6 pb-6">
          <div class="flex flex-col lg:flex-row gap-8 h-full">
            <div class="flex-1 flex justify-center items-center">
              <svg viewBox="0 0 732 530">
                <circle
                  cx="366"
                  cy="290"
                  r="18"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="1,1"
                  opacity="0.2"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="36"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="2,2"
                  opacity="0.3"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="54"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="2,3"
                  opacity="0.35"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="72"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="3,3"
                  opacity="0.4"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="90"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="3,4"
                  opacity="0.45"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="108"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="4,4"
                  opacity="0.5"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="125.99999999999999"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="4,5"
                  opacity="0.55"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="144"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="5,5"
                  opacity="0.6"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="162"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="5,6"
                  opacity="0.7"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="180"
                  fill="none"
                  stroke="#e5e7eb"
                  stroke-width="1"
                  stroke-dasharray="none"
                  opacity="1"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="8"
                  fill="none"
                  stroke="#6b7280"
                  stroke-width="1"
                  opacity="0.3"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="5"
                  fill="none"
                  stroke="#6b7280"
                  stroke-width="1"
                  opacity="0.5"
                ></circle>
                <circle cx="366" cy="290" r="3" fill="#6b7280"></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="45"
                  fill="none"
                  stroke="#10b981"
                  stroke-width="1.5"
                  opacity="0.2"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="90"
                  fill="none"
                  stroke="#3b82f6"
                  stroke-width="1.5"
                  opacity="0.2"
                ></circle>
                <circle
                  cx="366"
                  cy="290"
                  r="135"
                  fill="none"
                  stroke="#8b5cf6"
                  stroke-width="1.5"
                  opacity="0.2"
                ></circle>
                <g>
                  <line
                    x1="366"
                    y1="290"
                    x2="546"
                    y2="290"
                    stroke="#e5e7eb"
                    stroke-width="1"
                    opacity="0.7"
                  ></line>
                </g>
                <g>
                  <line
                    x1="366"
                    y1="290"
                    x2="366"
                    y2="470"
                    stroke="#e5e7eb"
                    stroke-width="1"
                    opacity="0.7"
                  ></line>
                </g>
                <g>
                  <line
                    x1="366"
                    y1="290"
                    x2="186"
                    y2="290"
                    stroke="#e5e7eb"
                    stroke-width="1"
                    opacity="0.7"
                  ></line>
                </g>
                <g>
                  <line
                    x1="366"
                    y1="290"
                    x2="365.99999999999994"
                    y2="110"
                    stroke="#e5e7eb"
                    stroke-width="1"
                    opacity="0.7"
                  ></line>
                </g>
                <g>
                  <path
                    d="
      M 366 290
      L 546 290
      A 180 180 0 0 1 366 470
      L 366 290
      Z
    "
                    fill="transparent"
                    fill-opacity="0"
                    stroke="transparent"
                    stroke-width="0"
                    class="cursor-pointer transition-all duration-300"
                  ></path>
                  <line
                    x1="366"
                    y1="290"
                    x2="546"
                    y2="290"
                    stroke="#ef4444"
                    stroke-width="1"
                    opacity="0.3"
                    class="transition-all duration-300"
                  ></line>
                  <g>
                    <rect
                      x="499.84776310850236"
                      y="458.84776310850236"
                      width="120"
                      height="20"
                      rx="3"
                      fill="white"
                      fill-opacity="0.9"
                      stroke="#ef4444"
                      stroke-width="1"
                      class="pointer-events-none"
                    ></rect>
                    <text
                      x="559.8477631085024"
                      y="468.84776310850236"
                      text-anchor="middle"
                      dominant-baseline="middle"
                      class="text-sm fill-gray-800 pointer-events-none font-bold"
                    >
                      Antivirus
                    </text>
                  </g>
                </g>
                <g>
                  <path
                    d="
      M 366 290
      L 366 470
      A 180 180 0 0 1 186 290
      L 366 290
      Z
    "
                    fill="transparent"
                    fill-opacity="0"
                    stroke="transparent"
                    stroke-width="0"
                    class="cursor-pointer transition-all duration-300"
                  ></path>
                  <line
                    x1="366"
                    y1="290"
                    x2="366"
                    y2="470"
                    stroke="#f59e0b"
                    stroke-width="1"
                    opacity="0.3"
                    class="transition-all duration-300"
                  ></line>
                  <g>
                    <rect
                      x="112.15223689149767"
                      y="458.84776310850236"
                      width="120"
                      height="20"
                      rx="3"
                      fill="white"
                      fill-opacity="0.9"
                      stroke="#f59e0b"
                      stroke-width="1"
                      class="pointer-events-none"
                    ></rect>
                    <text
                      x="172.15223689149767"
                      y="468.84776310850236"
                      text-anchor="middle"
                      dominant-baseline="middle"
                      class="text-sm fill-gray-800 pointer-events-none font-bold"
                    >
                      Firewall
                    </text>
                  </g>
                </g>
                <g>
                  <path
                    d="
      M 366 290
      L 186 290
      A 180 180 0 0 1 365.99999999999994 110
      L 366 290
      Z
    "
                    fill="transparent"
                    fill-opacity="0"
                    stroke="transparent"
                    stroke-width="0"
                    class="cursor-pointer transition-all duration-300"
                  ></path>
                  <line
                    x1="366"
                    y1="290"
                    x2="186"
                    y2="290"
                    stroke="#8b5cf6"
                    stroke-width="1"
                    opacity="0.3"
                    class="transition-all duration-300"
                  ></line>
                  <g>
                    <rect
                      x="112.15223689149761"
                      y="101.15223689149767"
                      width="120"
                      height="20"
                      rx="3"
                      fill="white"
                      fill-opacity="0.9"
                      stroke="#8b5cf6"
                      stroke-width="1"
                      class="pointer-events-none"
                    ></rect>
                    <text
                      x="172.1522368914976"
                      y="111.15223689149767"
                      text-anchor="middle"
                      dominant-baseline="middle"
                      class="text-sm fill-gray-800 pointer-events-none font-bold"
                    >
                      Browsers
                    </text>
                  </g>
                </g>
                <g>
                  <path
                    d="
      M 366 290
      L 365.99999999999994 110
      A 180 180 0 0 1 546 289.99999999999994
      L 366 290
      Z
    "
                    fill="transparent"
                    fill-opacity="0"
                    stroke="transparent"
                    stroke-width="0"
                    class="cursor-pointer transition-all duration-300"
                  ></path>
                  <line
                    x1="366"
                    y1="290"
                    x2="365.99999999999994"
                    y2="110"
                    stroke="#10b981"
                    stroke-width="1"
                    opacity="0.3"
                    class="transition-all duration-300"
                  ></line>
                  <g>
                    <rect
                      x="499.84776310850225"
                      y="101.15223689149761"
                      width="120"
                      height="20"
                      rx="3"
                      fill="white"
                      fill-opacity="0.9"
                      stroke="#10b981"
                      stroke-width="1"
                      class="pointer-events-none"
                    ></rect>
                    <text
                      x="559.8477631085022"
                      y="111.15223689149761"
                      text-anchor="middle"
                      dominant-baseline="middle"
                      class="text-sm fill-gray-800 pointer-events-none font-bold"
                    >
                      Devices
                    </text>
                  </g>
                </g>
                <line
                  x1="366"
                  y1="290"
                  x2="532.8930938220217"
                  y2="357.4291868148642"
                  stroke="#10b981"
                  stroke-width="2"
                  opacity="0.8"
                  class="pointer-events-none"
                >
                  <animate
                    attributeName="opacity"
                    values="0.8;0.4;0.8"
                    dur="2s"
                    repeatCount="indefinite"
                  ></animate>
                </line>
                <defs>
                  <radialGradient id="scanGradient">
                    <stop
                      offset="0%"
                      stop-color="#10b981"
                      stop-opacity="0.4"
                    ></stop>
                    <stop
                      offset="50%"
                      stop-color="#10b981"
                      stop-opacity="0.2"
                    ></stop>
                    <stop
                      offset="100%"
                      stop-color="#10b981"
                      stop-opacity="0"
                    ></stop>
                  </radialGradient>
                  <linearGradient
                    id="scanSweep"
                    x1="0%"
                    y1="0%"
                    x2="100%"
                    y2="0%"
                  >
                    <stop
                      offset="0%"
                      stop-color="#10b981"
                      stop-opacity="0"
                    ></stop>
                    <stop
                      offset="70%"
                      stop-color="#10b981"
                      stop-opacity="0.3"
                    ></stop>
                    <stop
                      offset="100%"
                      stop-color="#10b981"
                      stop-opacity="0"
                    ></stop>
                  </linearGradient>
                  <radialGradient id="waveGradient1">
                    <stop
                      offset="0%"
                      stop-color="#3b82f6"
                      stop-opacity="0.6"
                    ></stop>
                    <stop
                      offset="50%"
                      stop-color="#3b82f6"
                      stop-opacity="0.3"
                    ></stop>
                    <stop
                      offset="100%"
                      stop-color="#3b82f6"
                      stop-opacity="0"
                    ></stop>
                  </radialGradient>
                  <radialGradient id="waveGradient2">
                    <stop
                      offset="0%"
                      stop-color="#8b5cf6"
                      stop-opacity="0.5"
                    ></stop>
                    <stop
                      offset="50%"
                      stop-color="#8b5cf6"
                      stop-opacity="0.2"
                    ></stop>
                    <stop
                      offset="100%"
                      stop-color="#8b5cf6"
                      stop-opacity="0"
                    ></stop>
                  </radialGradient>
                  <radialGradient id="waveGradient3">
                    <stop
                      offset="0%"
                      stop-color="#10b981"
                      stop-opacity="0.4"
                    ></stop>
                    <stop
                      offset="50%"
                      stop-color="#10b981"
                      stop-opacity="0.2"
                    ></stop>
                    <stop
                      offset="100%"
                      stop-color="#10b981"
                      stop-opacity="0"
                    ></stop>
                  </radialGradient>
                </defs>
                <path
                  d="
                  M 366 290
                  L 532.8930938220217 357.4291868148642
                  A 180 180 0 0 0 531.6908736214393 219.66839687193072
                  L 366 290
                  Z
                "
                  fill="url(#scanSweep)"
                  opacity="0.6"
                  class="pointer-events-none"
                ></path>
                <circle
                  cx="366"
                  cy="290"
                  r="0"
                  fill="url(#waveGradient1)"
                  class="pointer-events-none"
                >
                  <animate
                    attributeName="r"
                    values="0;400;0"
                    dur="4s"
                    repeatCount="indefinite"
                    begin="0s"
                  ></animate>
                  <animate
                    attributeName="opacity"
                    values="0.6;0;0"
                    dur="4s"
                    repeatCount="indefinite"
                    begin="0s"
                  ></animate>
                </circle>
                <circle
                  cx="366"
                  cy="290"
                  r="0"
                  fill="url(#waveGradient2)"
                  class="pointer-events-none"
                >
                  <animate
                    attributeName="r"
                    values="0;400;0"
                    dur="4s"
                    repeatCount="indefinite"
                    begin="1.33s"
                  ></animate>
                  <animate
                    attributeName="opacity"
                    values="0.5;0;0"
                    dur="4s"
                    repeatCount="indefinite"
                    begin="1.33s"
                  ></animate>
                </circle>
                <circle
                  cx="366"
                  cy="290"
                  r="0"
                  fill="url(#waveGradient3)"
                  class="pointer-events-none"
                >
                  <animate
                    attributeName="r"
                    values="0;400;0"
                    dur="4s"
                    repeatCount="indefinite"
                    begin="2.66s"
                  ></animate>
                  <animate
                    attributeName="opacity"
                    values="0.4;0;0"
                    dur="4s"
                    repeatCount="indefinite"
                    begin="2.66s"
                  ></animate>
                </circle>
                <g>
                  <circle
                    cx="428.3538290724796"
                    cy="326"
                    r="6"
                    fill="#10b981"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                  </circle>
                  <circle
                    cx="428.3538290724796"
                    cy="326"
                    r="4"
                    fill="#10b981"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                  </circle>
                </g>
                <g>
                  <circle
                    cx="420"
                    cy="383.5307436087194"
                    r="6"
                    fill="#ef4444"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                  </circle>
                  <circle
                    cx="420"
                    cy="383.5307436087194"
                    r="4"
                    fill="#ef4444"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                  </circle>
                </g>
                <g>
                  <circle
                    cx="338.44679286971353"
                    cy="356.51932634081265"
                    r="6"
                    fill="#10b981"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                  </circle>
                  <circle
                    cx="338.44679286971353"
                    cy="356.51932634081265"
                    r="4"
                    fill="#10b981"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                  </circle>
                </g>
                <g>
                  <circle
                    cx="289.6324676318529"
                    cy="366.3675323681471"
                    r="6"
                    fill="#ef4444"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                  </circle>
                  <circle
                    cx="289.6324676318529"
                    cy="366.3675323681471"
                    r="4"
                    fill="#ef4444"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                  </circle>
                </g>
                <g>
                  <circle
                    cx="232.96134731837472"
                    cy="345.10641426057293"
                    r="6"
                    fill="#10b981"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="1s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="1s"
                    ></animate>
                  </circle>
                  <circle
                    cx="232.96134731837472"
                    cy="345.10641426057293"
                    r="4"
                    fill="#10b981"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="1s"
                    ></animate>
                  </circle>
                </g>
                <g>
                  <circle
                    cx="303.6461709275204"
                    cy="254"
                    r="6"
                    fill="#10b981"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                  </circle>
                  <circle
                    cx="303.6461709275204"
                    cy="254"
                    r="4"
                    fill="#10b981"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                  </circle>
                </g>
                <g>
                  <circle
                    cx="311.99999999999994"
                    cy="196.46925639128065"
                    r="6"
                    fill="#10b981"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                  </circle>
                  <circle
                    cx="311.99999999999994"
                    cy="196.46925639128065"
                    r="4"
                    fill="#10b981"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                  </circle>
                </g>
                <g>
                  <circle
                    cx="402"
                    cy="227.64617092752042"
                    r="6"
                    fill="#10b981"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                  </circle>
                  <circle
                    cx="402"
                    cy="227.64617092752042"
                    r="4"
                    fill="#10b981"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0s"
                    ></animate>
                  </circle>
                </g>
                <g>
                  <circle
                    cx="459.5307436087194"
                    cy="235.99999999999994"
                    r="6"
                    fill="#10b981"
                    opacity="0.2"
                    class="pointer-events-none transition-all duration-300 opacity-20"
                  >
                    <animate
                      attributeName="r"
                      values="6;8;6"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                    <animate
                      attributeName="opacity"
                      values="0.2;0.02;0.2"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                  </circle>
                  <circle
                    cx="459.5307436087194"
                    cy="235.99999999999994"
                    r="4"
                    fill="#10b981"
                    stroke="white"
                    stroke-width="1"
                    class="cursor-pointer transition-all duration-200 opacity-100"
                  >
                    <animate
                      attributeName="r"
                      values="4;5;4"
                      dur="3s"
                      repeatCount="indefinite"
                      begin="0.5s"
                    ></animate>
                  </circle>
                </g>
              </svg>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
